/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamofausto;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author edgar
 */
public class MantPrestamos extends javax.swing.JFrame {
        Date fechaActual = new Date();
    /**
     * Creates new form MantPrestamos
     */
    public MantPrestamos() {
        initComponents();setLocationRelativeTo(null);
            setResizable(false);
         this.getContentPane().setBackground(Color.WHITE);
        
        fecha_inicio.setDate(fechaActual);
        fecha_final.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        nomCli = new javax.swing.JLabel();
        nomFia = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        garantia = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        id_cliente = new javax.swing.JTextField();
        id_fiador = new javax.swing.JTextField();
        estado = new javax.swing.JCheckBox();
        fecha_inicio = new com.toedter.calendar.JDateChooser();
        plazo = new javax.swing.JTextField();
        fecha_final = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prestamosTabla = new javax.swing.JTable();
        monto = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        taza = new javax.swing.JTextField();
        cuota = new javax.swing.JTextField();
        foto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("MANTENIMIENTO PRESTAMO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 90, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("ID:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        nomCli.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nomCli.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(nomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        nomFia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nomFia.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(nomFia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Estado:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Fecha inicio:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Plazo:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("Fecha final:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Tipo garantia:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel1.add(garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 142, 40));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 142, -1));

        id_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_clienteKeyReleased(evt);
            }
        });
        jPanel1.add(id_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 142, -1));

        id_fiador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_fiadorKeyReleased(evt);
            }
        });
        jPanel1.add(id_fiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 142, -1));
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, -1));
        jPanel1.add(fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, 40));

        plazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazoActionPerformed(evt);
            }
        });
        plazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                plazoKeyReleased(evt);
            }
        });
        jPanel1.add(plazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 142, -1));
        jPanel1.add(fecha_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Monto:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Balance:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, 30));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("Taza:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 102));
        jLabel28.setText("Cuota:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, 30));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 102));
        jLabel29.setText("Foto:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, 20));

        prestamosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_prestamo_cuota", "Num_cuota", "Id Cuota", "Fecha cuota", "Valor cuota", "Valor amortizacion", "Valor interes", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prestamosTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 710, 250));

        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montoKeyReleased(evt);
            }
        });
        jPanel1.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 142, -1));
        jPanel1.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 142, -1));

        taza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tazaKeyReleased(evt);
            }
        });
        jPanel1.add(taza, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 142, -1));

        cuota.setEditable(false);
        jPanel1.add(cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 142, 40));
        jPanel1.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 160, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, 50));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("Id cliente:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 102));
        jLabel31.setText("Id fiador:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plazoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plazoKeyReleased
       if(plazo.getText().equals("")){
          fecha_inicio.setDate(fechaActual);
          return;
       }
      
      Calendar calendario = Calendar.getInstance();
      calendario.setTime(fecha_inicio.getDate());
      calendario.add(calendario.MONTH, Integer.parseInt(plazo.getText()));
      fecha_final.setDate(calendario.getTime());
    }//GEN-LAST:event_plazoKeyReleased

    private void plazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plazoActionPerformed

    
     public void limpiarCampos(boolean borraId){
        if(borraId){
          id.setText("");
        }
        id_cliente.setText("");
        id_fiador.setText("");
        plazo.setText("");
        fecha_inicio.setDate(null);
        fecha_final.setDate(null);
        garantia.setText("");
        monto.setText("");
        balance.setText("");
        taza.setText("");
        cuota.setText("");
        foto.setText("");
        nomCli.setText("");
        nomFia.setText("");
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      MetodosGenerales metodos = new MetodosGenerales ();
      SimpleDateFormat fomato_fecha = new SimpleDateFormat("MM/dd/YYYY");
      String fecha_Inicio = fomato_fecha.format(fecha_inicio.getCalendar().getTime());
      String fecha_Final = fomato_fecha.format(fecha_final.getCalendar().getTime());
      String estadoString = estado.isSelected() ? "True" : "False";
      String datos =id.getText()+"~"+id_cliente.getText()+"~"+id_fiador.getText()+"~"+estadoString+"~"+fecha_Inicio+"~"+plazo.getText()+"~"+fecha_Final+"~"+garantia.getText()+"~"+monto.getText()+"~"+balance.getText()+"~"+taza.getText()+"~"+cuota.getText()+"~"+foto.getText();
      metodos.registrar("Prestamos.txt", datos);
      JOptionPane.showMessageDialog(null,"Se ha registrado correctamente.");

      int plazoInteger = Integer.parseInt(plazo.getText());
    
       Calendar calendario = Calendar.getInstance();
       Date fecha = fecha_inicio.getDate();
       calendario.setTime(fecha);
       
       DecimalFormat df = new DecimalFormat("#.00");
       
       double montoPrestamo = Double.parseDouble(monto.getText());
       double valor_interes = ( montoPrestamo * Integer.parseInt(taza.getText()) / 100 );
       double valorCuota  = ( Integer.parseInt(monto.getText())  / Integer.parseInt(plazo.getText()) )  + valor_interes;
       double valorAutomizacion = valorCuota - valor_interes;
       
        ArrayList vector = new ArrayList();
       
       
      for(int i=1;i<=plazoInteger;i++){
         String fechaCuota = fomato_fecha.format(calendario.getTime());
         String CUOTAS = id.getText()+"~"+String.valueOf(i)+"~"+id_cliente.getText()+"~"+fechaCuota+"~"+df.format(valorCuota)+"~"+df.format(valorAutomizacion)+"~"+df.format(valor_interes)+"~"+"true";
         String datosCuotas =CUOTAS;
         vector.add(CUOTAS);
         metodos.registrar("Cuotas_Prestamos.txt", datosCuotas);
         calendario.add(calendario.MONTH, 1);
         
         montoPrestamo -=valorAutomizacion;
          valor_interes = Math.abs( (montoPrestamo * Integer.parseInt(taza.getText()) / 100 ));
         valorAutomizacion = valorCuota - valor_interes;
         

     }
         
         try{
                FileOutputStream archivo = new   FileOutputStream ("cuota prestamos"+id.getText()+".pdf");
                Document doc = new Document();
                PdfWriter.getInstance(doc, archivo);
                doc.open();
                doc.add(metodos.encabezado("Prestamo Id: " + id.getText() +  "Cliente: " + nomCli.getText()+"\r\n"));
                
                doc.add(metodos.informacion("Fecha inicio : " + fecha_Inicio + " Fecha final: " +  fecha_Final+"\r\n"));

                for (Object CuotaPDF : vector) { 
                doc.add(metodos.informacion("Número cuota: " + CuotaPDF.toString().split("~")[1] + " Fecha cuota: " +  CuotaPDF.toString().split("~")[3]  + "Valor cuota "  + CuotaPDF.toString().split("~")[4]   + " Valor amortizacion "  + CuotaPDF.toString().split("~")[5] + " Valor interes "  + CuotaPDF.toString().split("~")[6]  +"\r\n"));
               }
                doc.close();

            }catch(FileNotFoundException | DocumentException ex){

                
            }
            limpiarCampos(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
      MetodosGenerales metodos = new MetodosGenerales(); 
     String datos = metodos.validarID("Prestamos.txt", id.getText());
     if(datos.equals("no")){
         limpiarCampos(false);
     }else{
        id_cliente.setText(datos.split("~")[1]);
        id_fiador.setText(datos.split("~")[2]);
        Date fecha_Inicio = new Date(datos.split("~")[4]); 
        fecha_inicio.setDate(fecha_Inicio);
        plazo.setText(datos.split("~")[5]);
        Date fecha_Final = new Date(datos.split("~")[6]); 
        fecha_final.setDate(fecha_Final);
        garantia.setText(datos.split("~")[7]);
        monto.setText(datos.split("~")[8]);
        balance.setText(datos.split("~")[9]);
        taza.setText(datos.split("~")[10]);
        cuota.setText(datos.split("~")[11]);
        foto.setText(datos.split("~")[12]);
     }
         metodos.LlenarTablaModel("Cuotas_Prestamos.txt",prestamosTabla,8,id.getText(),0);


    }//GEN-LAST:event_idKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void montoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyReleased
         if(monto.getText().equals("")){
           balance.setText("");
           taza.setText("");
           cuota.setText("");
       }else{
           balance.setText(monto.getText());
           if(taza.getText().equals("")==false){
             calcularCuota();
           }
       }        
       
    }//GEN-LAST:event_montoKeyReleased

     public void calcularCuota(){
         try{
            if(taza.getText().equals("")==false){
            int valor_interes = ( Integer.parseInt(monto.getText()) * Integer.parseInt(taza.getText()) / 100 );
            int valorCuota  = ( Integer.parseInt(monto.getText())  / Integer.parseInt(plazo.getText()) )  + valor_interes;
                cuota.setText(String.valueOf(valorCuota));
        }
            
        }catch(Exception e){
        }
   }
     
    private void tazaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tazaKeyReleased
       calcularCuota();
    }//GEN-LAST:event_tazaKeyReleased

    private void id_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_clienteKeyReleased
         MetodosGenerales usuario= new MetodosGenerales();
        String consulta=usuario.validarID("Clientes.txt", id_cliente.getText());
        if(consulta.equals("no")){
            nomCli.setText("cliente no existe");
        }else{ 
             nomCli.setText(consulta.split("~")[1]);
        }
    }//GEN-LAST:event_id_clienteKeyReleased

    private void id_fiadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_fiadorKeyReleased
        MetodosGenerales usuario= new MetodosGenerales();
        String consulta=usuario.validarID("Fiadores.txt", id_fiador.getText());
        if(consulta.equals("no")){
            nomFia.setText("fiador no existe");
        }else{ 
             nomFia.setText(consulta.split("~")[1]);
        }    
    }//GEN-LAST:event_id_fiadorKeyReleased

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JTextField cuota;
    private javax.swing.JCheckBox estado;
    private com.toedter.calendar.JDateChooser fecha_final;
    private com.toedter.calendar.JDateChooser fecha_inicio;
    private javax.swing.JTextField foto;
    private javax.swing.JTextField garantia;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JTextField id_fiador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monto;
    private javax.swing.JLabel nomCli;
    private javax.swing.JLabel nomFia;
    private javax.swing.JTextField plazo;
    private javax.swing.JTable prestamosTabla;
    private javax.swing.JTextField taza;
    // End of variables declaration//GEN-END:variables
}
