/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamofausto;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class MovimientoCobro extends javax.swing.JFrame {

    /**
     * Creates new form MovimientoCobro
     */
    
    public MovimientoCobro() {
        initComponents();
        setLocationRelativeTo(null);
             setResizable(false);
         this.getContentPane().setBackground(Color.WHITE);
        
            Date fechaActual = new Date();
            fecha.setDate(fechaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fecha = new com.toedter.calendar.JDateChooser();
        Valor = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        Cliente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        concepto = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuotasCliente = new javax.swing.JTable();
        mensaje = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 222, -1));

        Valor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });
        jPanel1.add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 223, -1));

        Id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdKeyReleased(evt);
            }
        });
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 150, -1));

        Cliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClienteKeyReleased(evt);
            }
        });
        jPanel1.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 220, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Valor:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Cliente:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Fecha:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("ID:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 100, 20));

        concepto.setColumns(20);
        concepto.setRows(5);
        jScrollPane2.setViewportView(concepto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 220, 100));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Concepto:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        cuotasCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cuotasCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID prestamo", "Num cuota", "Fecha", "Valor cuota", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cuotasCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 600, 150));

        mensaje.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mensaje.setForeground(new java.awt.Color(0, 0, 102));
        mensaje.setText("CREANDO");
        jPanel1.add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 60, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Movimiento de cobros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void IdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyReleased
        MetodosGenerales usuario= new MetodosGenerales();
        String consulta=usuario.validarID("Cobros_prestamos.txt", Id.getText());
        if(consulta.equals("no")){
            Date fechaHoy = new Date();
            fecha.setDate(fechaHoy);
            Cliente.setText("");
            Valor.setText("");
            mensaje.setText("CREANDO");
        }else{
            Date fecha_entrada = new Date(consulta.split("~")[1]);
            fecha.setDate(fecha_entrada);
            Cliente.setText(consulta.split("~")[2]);
            Valor.setText(consulta.split("~")[3]);
            mensaje.setText("Modificando");
        }
    }//GEN-LAST:event_IdKeyReleased

    private void ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteKeyReleased
        DefaultTableModel  modelo =(DefaultTableModel) cuotasCliente.getModel();
        modelo.setRowCount(0);
        cuotasCliente.setModel(modelo);
        if(Cliente.getText().equals("")){
            return;
        }

        MetodosGenerales general = new MetodosGenerales ();
        ArrayList<String> vector = new ArrayList();

        String dato_cliente = general.validarID("Clientes.txt",Cliente.getText());
        if(dato_cliente.equals("no")){
            JOptionPane.showMessageDialog(null,"Error el cliente no existe","Error",JOptionPane.ERROR_MESSAGE);
            return;

        }
//        else if(dato_cliente.split("~")[9].equals("true")==false || dato_cliente.split("~")[10].equals("Socio Activo")==false){
//            JOptionPane.showMessageDialog(null,"Error el cliente debe ser un socio activo y tener el status en true","Error",JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        vector=general.LlenarTablaCondicion("Cuotas_Prestamos.txt",2,Cliente.getText());
        String datos [ ] = new String [5];
        if(vector.size()<1){
            JOptionPane.showMessageDialog(null,"Error el cliente no existe en el archivo cuotas prestamos","Error",JOptionPane.ERROR_MESSAGE);

        }
        
          SimpleDateFormat formato = new SimpleDateFormat("MM/dd/YYYY");
            String fechaD=formato.format(fecha.getCalendar().getTime());
            Date fechaActual = new Date(fechaD);
              
        for (int i = 0; i <vector.size(); i++) {
             Date fechaCuota = new Date(vector.get(i).split("~")[3]);
            if( (fechaActual.after(fechaCuota) || fechaActual.equals(fechaCuota)) && vector.get(i).split("~")[7].equals("true")){
                datos[0]=vector.get(i).split("~")[0];
                datos[1]=vector.get(i).split("~")[1];
                datos[2]=vector.get(i).split("~")[3];
                datos[3]=vector.get(i).split("~")[4];
                datos[4]=vector.get(i).split("~")[7];
                modelo.addRow(datos);
            }

        }
    }//GEN-LAST:event_ClienteKeyReleased

    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorActionPerformed

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Id.getText().equals("")==false && fecha.getCalendar()!=null && Cliente.getText().equals("")==false && Valor.getText().equals("")==false && concepto.getText().equals("")==false  ){
            MetodosGenerales general = new MetodosGenerales ();
            String validar=general.validarID("Cobros_prestamos.txt",Id.getText());
            SimpleDateFormat fomato_fecha = new SimpleDateFormat("MM/dd/YYYY");
            String fechaCuota = fomato_fecha.format(fecha.getCalendar().getTime());

            if(validar.equals("no")){
                if(cuotasCliente.getRowCount()==0){
                    JOptionPane.showMessageDialog(null,"La tabla de cuotas esta vacia, por favor llenarlo","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                general.registrar("Cobros_prestamos.txt",Id.getText()+"~"+fechaCuota+"~"+Cliente.getText()+"~"+Valor.getText()+"~"+concepto.getText()+"~"+"false");
                Double abono = Double.parseDouble(Valor.getText());
                 for(int i=0;i<cuotasCliente.getRowCount();i++){
                      String valorCuota = "";
                        Double ValorCuota = Double.parseDouble(cuotasCliente.getValueAt(i, 3).toString());
                        if(abono>=ValorCuota){
                            valorCuota = ValorCuota.toString();
                            abono-=ValorCuota;
                      
                        }else{
                           valorCuota = String.valueOf(abono);
                            abono=0.0;
                        }
                           int secuencia = i+1;
                        general.registrar("Detalles_Cobros.txt",Id.getText()+"~"+secuencia+"~"+cuotasCliente.getValueAt(i, 0).toString()+"~"+cuotasCliente.getValueAt(i, 1).toString()+"~"+valorCuota+"~"+"0"+"~"+"0"+"~"+"0");
                           
                        String validarCuota=general.verificarCuotaTrue(cuotasCliente.getValueAt(i, 0).toString(),cuotasCliente.getValueAt(i, 1).toString());
                        if(validarCuota.equals("no")==false){
                            validarCuota = validarCuota.split("~")[0]+"~"+validarCuota.split("~")[1]+"~"+validarCuota.split("~")[2]+"~"+validarCuota.split("~")[3]+"~"+validarCuota.split("~")[4]+"~"+validarCuota.split("~")[5]+"~"+validarCuota.split("~")[6]+"~"+"false"; 
                            general.modificar("Cuotas_Prestamos.txt", validarCuota.split("~")[0], validarCuota);
                        
                        }
                        
                         if(abono<=0.0){
                            break;
                        }
                      
                       
                 }
                 
                 
                Id.setText("");
                fecha.setDate(null);
                Date fechaActual = new Date();
                fecha.setDate(fechaActual);
                Cliente.setText("");
                Valor.setText("");
                concepto.setText("");
                mensaje.setText("CREANDO");
                DefaultTableModel  modelo =(DefaultTableModel) cuotasCliente.getModel();
                modelo.setRowCount(0);
                cuotasCliente.setModel(modelo);

            }else{
                general.modificar("Detalles_Cobros.txt",Id.getText(),Id.getText()+"~"+fomato_fecha+"~"+Cliente.getText()+"~"+Valor.getText()+"~"+"false");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios, por favor llenarlo","Errro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientoCobro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Valor;
    private javax.swing.JTextArea concepto;
    private javax.swing.JTable cuotasCliente;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
